
default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: 

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Thinknetica_3_development

test:
  <<: *default
  database: Thinknetica_3_test
